"""empty message

Revision ID: 392f52ff659c
Revises: 
Create Date: 2020-09-15 15:35:21.287118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392f52ff659c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ver_num', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('first_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools_nav',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('first_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['first_id'], ['first_nav.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=100), nullable=False),
    sa.Column('tool_url', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['tools_nav.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_info')
    op.drop_table('tools_nav')
    op.drop_table('links')
    op.drop_table('first_nav')
    op.drop_table('changelog')
    # ### end Alembic commands ###
